name: Setup CI
description: |
  This action sets up Node.js and installs dependencies for the project.
  It also configures caching for TurboRepo to speed up the build process.

inputs:
  node-version:
    description: 'Node.js version'
    required: true
    default: '24'

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        cache: 'npm'
        node-version: ${{ inputs.node-version }}

    - name: Setup turbo
      uses: actions/cache@v4
      with:
        path: |
          .turbo
          **/.turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-

    - name: Install global dependencies
      shell: bash
      run: npm i -g turbo prettier typescript @arethetypeswrong/cli @changesets/cli @changesets/changelog-github

    - name: Install dependencies
      shell: bash
      run: npm ci
