volumes:
  ydb-certs:

networks:
  default:
    driver: bridge
    enable_ipv6: true

services:
  sdk:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: sdk

    volumes:
      - ydb-certs:/ydb_certs
      - ../:/workspaces/ydb-js-sdk:cached

    environment:
      - YDB_VERSION=trunk
      - YDB_STATIC_CREDENTIALS_USER=root
      - YDB_STATIC_CREDENTIALS_PASSWORD=1234
      - YDB_STATIC_CREDENTIALS_ENDPOINT=grpc://ydb:2136
      - YDB_CONNECTION_STRING=grpc://ydb:2136/local
      - YDB_CONNECTION_STRING_SECURE=grpcs://ydb:2135/local
      - YDB_SSL_ROOT_CERTIFICATES_FILE=/ydb_certs/ca.pem

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  ydb:
    image: ydbplatform/local-ydb:trunk@sha256:74a086d193a117e911115a830e3f1f01816b9d85df1305b0bc923de14b1bcac5
    restart: unless-stopped
    hostname: ydb
    platform: linux/amd64

    ports:
      - 2135
      - 2136
      - 8765

    volumes:
      - ydb-certs:/ydb_certs

    environment:
      - YDB_USE_IN_MEMORY_PDISKS=true
      - YDB_ENABLE_COLUMN_TABLES=true
      - GRPC_TLS_PORT=2135
      - GRPC_PORT=2136
      - MON_PORT=8765

  prometheus:
    image: prom/prometheus:v3.3.0
    restart: unless-stopped
    hostname: prometheus
    platform: linux/amd64

    ports:
      - 9090

    volumes:
      - ydb-certs:/ydb_certs
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
