name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    concurrency:
      group: lint-${{ github.event_name }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
      - run: npm run lint

  build:
    name: Build
    runs-on: ubuntu-latest
    concurrency:
      group: build-${{ github.event_name }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
      - run: npm run build
      - run: npm run attw
      - run: npm run check:surface --workspace=@ydbjs/drizzle-adapter

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    concurrency:
      group: ${{ github.event_name }}-${{ github.ref }}-${{ matrix.node-version }}
      cancel-in-progress: true

    strategy:
      fail-fast: false
      matrix:
        node-version: ['latest', 'lts/*', 'lts/-1', 'lts/-2']

    services:
      ydb:
        image: ydbplatform/local-ydb:25.2
        ports:
          - 2135:2135
          - 2136:2136
          - 8765:8765
        volumes:
          - /tmp/ydb_certs:/ydb_certs
        env:
          YDB_ENABLE_COLUMN_TABLES: true
          YDB_USE_IN_MEMORY_PDISKS: true
        options: '-h localhost'

    env:
      YDB_STATIC_CREDENTIALS_USER: root
      YDB_STATIC_CREDENTIALS_PASSWORD: 1234
      YDB_STATIC_CREDENTIALS_ENDPOINT: grpc://localhost:2136
      YDB_CONNECTION_STRING: grpc://localhost:2136/local
      YDB_CONNECTION_STRING_SECURE: grpcs://localhost:2135/local
      YDB_SSL_ROOT_CERTIFICATES_FILE: /tmp/ydb_certs/ca.pem

    steps:
      # Checkout the repository
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}

      - name: Test
        if: matrix.node-version != 'lts/*'
        run: npm run test

      - name: Test with coverage
        if: matrix.node-version == 'lts/*'
        run: npm run coverage

      - name: Upload coverage to Codecov
        if: matrix.node-version == 'lts/*'
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
          fail_ci_if_error: false

      - name: Publish coverage report to Surge
        if: matrix.node-version == 'lts/*'
        continue-on-error: true
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            domain="ydb-js-sdk-coverage-pr-${{ github.event.pull_request.number }}.surge.sh"
          else
            domain="ydb-js-sdk-coverage.surge.sh"
          fi

          npx surge ./coverage "$domain"
          echo "### :bar_chart: [Coverage report](https://$domain)" >> "$GITHUB_STEP_SUMMARY"
