name: Node.js CI

on:
  pull_request:
    branches: [ '**' ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x]

    services:
      ydb:
        image: cr.yandex/yc/yandex-docker-local-ydb:latest
        ports:
          - 2135:2135
        volumes:
          - /tmp/ydb_certs:/ydb_certs
        env:
          YDB_LOCAL_SURVIVE_RESTART: true
          YDB_USE_IN_MEMORY_PDISKS: true
        options: '-h localhost'

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build library
      run: npm run build:lib
    - name: Prepare examples build
      run: npm link && cd examples && npm ci && npm link ydb-sdk && cd ..
    - name: Build examples
      run: npm run build:examples
    - name: Run tests
      run: npm run test:all
      env:
        YDB_SSL_ROOT_CERTIFICATES_FILE: /tmp/ydb_certs/ca.pem
