#!/usr/bin/env bash
set -euo pipefail

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

git stash --keep-index --include-untracked -q
cleanup() {
	git stash pop -q 2>/dev/null || true
}
trap cleanup EXIT

# Lint all selected files
echo "$FILES" | xargs ./node_modules/.bin/oxlint --fix --quiet
LINT_EXIT=$?

# Prettify all selected files
echo "$FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit $LINT_EXIT
